# --------------------------------------------------
# Arquivo de Configuração do Projeto: _quarto.yml
# --------------------------------------------------

# Define o tipo de projeto como 'book'
project:
  type: book

# Metadados específicos do livro
book:
  title: "Introdução à Estatística com R para Biólogos"
  author: "Fernando Andrade"
  # date: "today" # Usa a data atual a cada renderização

  # Lista e ordem dos capítulos do livro
  chapters:
    - file: index.qmd
    
    - part: parte1-intro.qmd
      chapters:
        - 01-intro-r.qmd
        - 02-tidyverse.qmd
    - part: "Fundamentos do Pensamento Estatístico"
      chapters:
        - 03-probabilidade.qmd
        - 04-inferencia.qmd
        - 05-delineamento.qmd
    - part: "Modelagem Estatística de Dados Biológicos"
      chapters:
        - 06-lm.qmd
        - 07-lmm.qmd
        - 08-lme4.qmd
        - 09-glmm.qmd
        - 10-interpretacao.qmd
    - part: "Aplicações Práticas e Recursos"
    
    - references.qmd    # Onde a lista de referências será gerada

# Arquivo de bibliografia (formato BibTeX)
bibliography: references.bib
csl: abnt.csl

# Definindo o idioma do documento para o Quarto
lang: pt-br

# Opções de formato de saída
format:
  # Configurações para o PDF
  pdf:
    documentclass: scrreprt   # Classe do documento LaTeX
    code-block-font-size: small
    toc: true                 # Gera o sumário (Table of Contents)
    toc-title: "Sumário"
    mainfont: "Times New Roman"
    fontsize: 12pt
    number-sections: true     # Numera as seções
    link-citations: true
    colorlinks: true          # Deixa os links internos (sumário, citações)
                              # coloridos em vez de caixas
    
    # Aqui é onde você adiciona pacotes e comandos LaTeX
    include-in-header: header.tex
        
        
  # Você pode adicionar outros formatos aqui, como HTML
  # html:
  #   theme: cosmo
execute:
  fig-width: 6
  fig-height: 2.5
  fig-align: center

# Configurações do editor (opcional, para RStudio/VS Code)
editor: visual